### ISSUE TITLE
Coverage support

### ISSUE THREAD

**Issue by kaidokert** [codacy/codacy-cppcheck#16]
CPP projects should have a documented path to support coverage. 

https://github.com/eriwen/lcov-to-cobertura-xml

`pip install lcov_cobertura`

`python -m lcov_cobertura  ./cmake-build-debugcoverage/coverage.info`

I just tested this and and the conversion seems fine. I tried uploading with the java uploader as well. 
`java -jar codacy-coverage-reporter-4.0.3-assembly.jar report -l cpp --force-language -r coverage.xml`

Worked fine.

**Comment by rtfpessoa** [comment]
@kaidokert this project is only related to cppcheck and not c the language.

Regarding lcov you can use https://github.com/codacy/node-codacy-coverage#force-custom-language-eg-typescript-coffeescript-c- and pass the language manually.

If you have any questions regarding coverage please contact us through the in app chat or `support at codacy dot com`.
