### ISSUE TITLE
codacy config misra

### ISSUE THREAD

**Issue by binarymaker** [codacy/codacy-cppcheck#37]
how can i enable all newly added misra rules (code patterns) to repos using .codacy.yml?
please share example config files.

**Comment by binarymaker** [comment]
i found this https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns to enable patterns
but its not clear too

**Comment by mrfyda** [comment]
Hey @binarymaker 

If I'm not mistaken, cppcheck does not allow configuration through a configuration file.

You can configure MISRA rules through the Codacy UI. The rules will appear under cppcheck and be prefixed with MISRA.

**Comment by binarymaker** [comment]
thank you for response. i did same way, i enable code patterns in my account global UI settings and reset my repo settings to global
