### ISSUE TITLE
[TS-249] Update cppcheck version

### ISSUE THREAD

**Issue by ajtribick** [codacy/codacy-cppcheck#56]
It would be nice not to keep getting dinged for "suspicious operator ','" when using Eigen matrix initialization, which appears to have been fixed sometime between cppcheck version 2.2 and the current one.

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching out to our community!

I bumped [cppcheck to version 2.10](https://github.com/codacy/codacy-cppcheck/pull/57).

Best,
Stefan

**Comment by ajtribick** [comment]
Thanks for the fast update, much appreciated!
